### ISSUE TITLE
Release as an npm package

### ISSUE THREAD

**Issue by MikeRalphson** [codebox/regex_parser#1]
Hi, thanks for this library.

I was wondering if you might package this up as an npm module?

This might sound like a strange request when Node.js has its own native regex implementation, but I have a concrete requirement.

The OpenAPI specification (formerly known as Swagger) [mandates](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#properties) that `pattern` properties meet the ECMA 262 standard for regexes, which does not include look-behinds.

Node 8.10.0 introduces look-behinds natively, so it is no longer possible to validate a regular expression meets the OpenAPI requirement by trying to instantiate the regex and catching any exception.

Your library appears to offer this capability.

I'm also happy to fork and package it myself if you don't want to.

**Comment by codebox** [comment]
I'm not sure if this library is full compliant with the regex spec for ECMA262 - I didn't design it to be, so if it is that would be a (happy) coincidence. If you're sure it meets your requirement I can package it up and publish to npm, but first please check the spec carefully to see that it does everything you need.

**Comment by MikeRalphson** [comment]
Ok thanks, will try and check it against the spec. Note [this](https://github.com/tc39/test262/tree/master/test/language/literals/regexp) may be useful.

**Comment by MikeRalphson** [comment]
Ok, I think I've hit a snag - doesn't support non-capturing groups. 

Just in case anyone else finds this issue, my fork wraps this as an npm package and the included tests pass. The ECMA262 tests use `/regex/` syntax to construct RegExps which makes it difficult to reuse them.
